### ISSUE TITLE
pictures and text files of results by example cases

### ISSUE THREAD

**Issue by stefano2734** [PyFR/PyFR-Test-Cases#10]
pictures  of results by example cases are only in documentation.

and some pictures should linked to readme.md as eye catcher in PyFR.

so the user can see better the possibilities of the software.

**Comment by FreddieWitherden** [comment]
As you note images can already be found in the documentation which is distributed separately.

This repository is exclusively for files which are required for running the test cases.  If a user wishes to see what the software is capable of they can look at the main website, the documentation, our seminars, or any of our associated publications.  No one is going to start off looking at the test cases repository.

**Comment by stefano2734** [comment]
I see in „about“ here  of PyFR and his cases 
no words at GitHub like 
CFD, fluid, Mach, flux, subsonic, hypersonic, Python, Mako and others.

there is no link to the method FR perhaps in Wikipedia or papers.
Like
https://www.researchgate.net/publication/309715679_A_Flux_Reconstruction_Approach_to_High-Order_Schemes_Including_Discontinuous_Galerkin_Methods

or
http://aero-comlab.stanford.edu/Papers/2017_handbook_num_ana_ch10.pdf
or
https://scholar.google.com/citations?user=ZXhGCtwAAAAJ&hl=en

so PyFR was only found by my other stars with GitHub  
Recommended for you
Not with search by words.
